
const char* DefaultInputIni = "; Only edit this file while game is closed, as game will overwrite any changes on exit\n\
; If you want to prevent the game from colliding with any of your binds, make sure BindFromInputIniOnly inside DQXIS-SDK.ini is set to true!\n\
\n\
[/Script/Engine.InputSettings]\n\
; Custom action bindings:\n\
ActionMappings=(ActionName=\"FirstPersonCamera\", Key=N)\n\
ActionMappings=(ActionName=\"EnterPartyChat\", Key=M)\n\
\n\
; MiddleMouseButton is usually bound to ToggleAutoRun\n\
; Feel free to comment this & uncomment/restore that binding below\n\
ActionMappings=(ActionName=\"FirstPersonCamera\", Key=MiddleMouseButton)\n\
\n\
ActionMappings=(ActionName=\"FirstPersonCamera\", Key=Gamepad_Special_Left)\n\
ActionMappings=(ActionName=\"EnterPartyChat\", Key=Gamepad_LeftThumbstick)\n\
\n\
; Default game bindings\n\
; Gamepad_FaceButton refers to the A/B/X/Y (X/Circle/Square/Triangle) on your gamepad, the direction decides which button\n\
ActionMappings=(ActionName=\"Action\",Key=Gamepad_FaceButton_Bottom)\n\
ActionMappings=(ActionName=\"Action\",Key=Gamepad_LeftTrigger)\n\
ActionMappings=(ActionName=\"Action\",Key=LeftMouseButton)\n\
ActionMappings=(ActionName=\"Action\",Key=E)\n\
ActionMappings=(ActionName=\"Action\",Key=V)\n\
ActionMappings=(ActionName=\"Brake\",Key=Gamepad_FaceButton_Left)\n\
ActionMappings=(ActionName=\"Brake\",Key=X)\n\
ActionMappings=(ActionName=\"Cancel\",Key=Gamepad_FaceButton_Right)\n\
ActionMappings=(ActionName=\"Cancel\",Key=RightMouseButton)\n\
ActionMappings=(ActionName=\"Cancel\",Key=Q)\n\
ActionMappings=(ActionName=\"Dash\",Key=Gamepad_RightTrigger)\n\
ActionMappings=(ActionName=\"Dash\",Key=LeftShift)\n\
;ActionMappings=(ActionName=\"FirstPersonCamera\",Key=Gamepad_Special_Left)\n\
ActionMappings=(ActionName=\"Jump\",Key=Gamepad_RightTrigger)\n\
ActionMappings=(ActionName=\"Jump\",Key=LeftShift)\n\
ActionMappings=(ActionName=\"JumpExtend\",Key=Gamepad_FaceButton_Right)\n\
ActionMappings=(ActionName=\"JumpExtend\",Key=SpaceBar)\n\
ActionMappings=(ActionName=\"OpenMainMenuWindow\",Key=Gamepad_FaceButton_Top)\n\
ActionMappings=(ActionName=\"OpenMainMenuWindow\",Key=Escape)\n\
ActionMappings=(ActionName=\"OpenShortcutMenu\",Key=Gamepad_Special_Right)\n\
ActionMappings=(ActionName=\"OpenShortcutMenu\",Key=I)\n\
ActionMappings=(ActionName=\"OpenWorldMap\",Key=Gamepad_FaceButton_Left)\n\
ActionMappings=(ActionName=\"OpenWorldMap\",Key=X)\n\
ActionMappings=(ActionName=\"PhotoMode\",Key=Gamepad_DPad_Up)\n\
ActionMappings=(ActionName=\"PhotoMode\",Key=P)\n\
ActionMappings=(ActionName=\"ResetCamera\",Key=Gamepad_RightThumbstick)\n\
ActionMappings=(ActionName=\"ResetCamera\",Key=C)\n\
ActionMappings=(ActionName=\"ResetCameraConvinationKeys\",Key=Gamepad_LeftShoulder)\n\
ActionMappings=(ActionName=\"ResetCameraConvinationKeys\",Key=Gamepad_RightShoulder)\n\
ActionMappings=(ActionName=\"ResetCameraKeys1\",Key=H)\n\
ActionMappings=(ActionName=\"ResetCameraKeys1\",Key=J)\n\
ActionMappings=(ActionName=\"SkipCutScene\",Key=Gamepad_FaceButton_Left)\n\
ActionMappings=(ActionName=\"SkipCutScene\",Key=X)\n\
;ActionMappings=(ActionName=\"ToggleAutoRun\",Key=Gamepad_LeftThumbstick)\n\
;ActionMappings=(ActionName=\"ToggleAutoRun\",Key=MiddleMouseButton)\n\
ActionMappings=(ActionName=\"ToggleAutoRun\",Key=Home)\n\
ActionMappings=(ActionName=\"MoveDown\",Key=Gamepad_FaceButton_Right)\n\
ActionMappings=(ActionName=\"MoveDown\",Key=Q)\n\
ActionMappings=(ActionName=\"DebugCamera_DecreaseFOV\",Key=Gamepad_DPad_Left)\n\
ActionMappings=(ActionName=\"DebugCamera_DecreaseSpeed\",Key=MouseScrollDown)\n\
ActionMappings=(ActionName=\"DebugCamera_FreezeRendering\",Key=Gamepad_FaceButton_Top)\n\
ActionMappings=(ActionName=\"DebugCamera_IncreaseFOV\",Key=Gamepad_DPad_Right)\n\
ActionMappings=(ActionName=\"DebugCamera_IncreaseSpeed\",Key=MouseScrollUp)\n\
ActionMappings=(ActionName=\"DebugCamera_Teleport\",Key=Gamepad_FaceButton_Bottom)\n\
ActionMappings=(ActionName=\"DebugCamera_ToggleControlTarget\",Key=Gamepad_RightThumbstick)\n\
ActionMappings=(ActionName=\"DebugCamera_ToggleDisplay\",Key=Gamepad_FaceButton_Left)\n\
ActionMappings=(ActionName=\"BattleMessageSkip\",Key=Gamepad_FaceButton_Bottom)\n\
ActionMappings=(ActionName=\"BattleMessageSkip\",Key=Gamepad_FaceButton_Right)\n\
ActionMappings=(ActionName=\"BattleMessageSkip\",Key=Gamepad_LeftTrigger)\n\
ActionMappings=(ActionName=\"BattleMessageSkip\",Key=Gamepad_DPad_Right)\n\
ActionMappings=(ActionName=\"BattleMessageSkip\",Key=Gamepad_DPad_Down)\n\
ActionMappings=(ActionName=\"BattleMessageSkip\",Key=Gamepad_DPad_Left)\n\
ActionMappings=(ActionName=\"BattleMessageSkip\",Key=Gamepad_DPad_Up)\n\
ActionMappings=(ActionName=\"DPad_Down\",Key=Gamepad_DPad_Down)\n\
ActionMappings=(ActionName=\"DPad_Down\",Key=Down)\n\
ActionMappings=(ActionName=\"DPad_Left\",Key=Gamepad_DPad_Left)\n\
ActionMappings=(ActionName=\"DPad_Left\",Key=Left)\n\
ActionMappings=(ActionName=\"DPad_Right\",Key=Gamepad_DPad_Right)\n\
ActionMappings=(ActionName=\"DPad_Right\",Key=Right)\n\
ActionMappings=(ActionName=\"DPad_Up\",Key=Gamepad_DPad_Up)\n\
ActionMappings=(ActionName=\"DPad_Up\",Key=Up)\n\
ActionMappings=(ActionName=\"UIButtonTop\",Key=Escape)\n\
ActionMappings=(ActionName=\"UIButtonTop\",Key=Gamepad_FaceButton_Top)\n\
ActionMappings=(ActionName=\"UIButtonLeft\",Key=Gamepad_FaceButton_Left)\n\
ActionMappings=(ActionName=\"UIButtonLeft\",Key=X)\n\
ActionMappings=(ActionName=\"UIButtonBottom\",Key=Gamepad_FaceButton_Bottom)\n\
ActionMappings=(ActionName=\"UIButtonBottom\",Key=LeftMouseButton)\n\
ActionMappings=(ActionName=\"UIButtonBottom\",Key=E)\n\
ActionMappings=(ActionName=\"UIButtonRight\",Key=Gamepad_FaceButton_Right)\n\
ActionMappings=(ActionName=\"UIButtonRight\",Key=Q)\n\
ActionMappings=(ActionName=\"UIButtonRight\",Key=RightMouseButton)\n\
ActionMappings=(ActionName=\"UIButtonOption\",Key=Gamepad_Special_Right)\n\
ActionMappings=(ActionName=\"UIButtonOption\",Key=I)\n\
ActionMappings=(ActionName=\"UIButtonSelect\",Key=Gamepad_Special_Left)\n\
ActionMappings=(ActionName=\"UIButtonSelect\",Key=R,bDebugOnly=True)\n\
ActionMappings=(ActionName=\"UIButtonL1\",Key=Gamepad_LeftShoulder)\n\
ActionMappings=(ActionName=\"UIButtonL1\",Key=H)\n\
ActionMappings=(ActionName=\"UIButtonL2\",Key=Gamepad_LeftTrigger)\n\
ActionMappings=(ActionName=\"UIButtonL2\",Key=LeftMouseButton)\n\
ActionMappings=(ActionName=\"UIButtonL2\",Key=V)\n\
ActionMappings=(ActionName=\"UIButtonL3\",Key=Gamepad_LeftThumbstick)\n\
ActionMappings=(ActionName=\"UIButtonL3\",Key=MiddleMouseButton)\n\
ActionMappings=(ActionName=\"UIButtonL3\",Key=Home)\n\
ActionMappings=(ActionName=\"UIButtonR1\",Key=Gamepad_RightShoulder)\n\
ActionMappings=(ActionName=\"UIButtonR1\",Key=J)\n\
ActionMappings=(ActionName=\"UIButtonR2\",Key=Gamepad_RightTrigger)\n\
ActionMappings=(ActionName=\"UIButtonR2\",Key=LeftShift)\n\
ActionMappings=(ActionName=\"UIButtonR3\",Key=Gamepad_RightThumbstick)\n\
ActionMappings=(ActionName=\"UIButtonR3\",Key=C)\n\
ActionMappings=(ActionName=\"UIDPadTop\",Key=Gamepad_DPad_Up)\n\
ActionMappings=(ActionName=\"UIDPadTop\",Key=Up)\n\
ActionMappings=(ActionName=\"UIDPadLeft\",Key=Gamepad_DPad_Left)\n\
ActionMappings=(ActionName=\"UIDPadLeft\",Key=Left)\n\
ActionMappings=(ActionName=\"UIDPadBottom\",Key=Gamepad_DPad_Down)\n\
ActionMappings=(ActionName=\"UIDPadBottom\",Key=Down)\n\
ActionMappings=(ActionName=\"UIDPadRight\",Key=Gamepad_DPad_Right)\n\
ActionMappings=(ActionName=\"UIDPadRight\",Key=Right)\n\
ActionMappings=(ActionName=\"UIDescButton\",Key=Gamepad_RightThumbstick)\n\
ActionMappings=(ActionName=\"UIWheelButton\",Key=Gamepad_RightThumbstick)\n\
ActionMappings=(ActionName=\"UIWheelButton\",Key=C)\n\
ActionMappings=(ActionName=\"PhotoModeSlideReset\",Key=Gamepad_LeftThumbstick)\n\
ActionMappings=(ActionName=\"PauseCancelKey\",Key=AnyKey)\n\
AxisMappings=(AxisName=\"LookUpMouse\",Key=MouseY,Scale=1.f,bDebugOnly=True)\n\
AxisMappings=(AxisName=\"LookUp\",Key=Gamepad_RightY,Scale=-1.f)\n\
AxisMappings=(AxisName=\"LookUp\",Key=L,Scale=-1.f)\n\
AxisMappings=(AxisName=\"LookUp\",Key=O,Scale=1.f)\n\
AxisMappings=(AxisName=\"MoveForward\",Key=Gamepad_LeftY,Scale=1.f)\n\
AxisMappings=(AxisName=\"MoveForward\",Key=W,Scale=1.f)\n\
AxisMappings=(AxisName=\"MoveForward\",Key=S,Scale=-1.f)\n\
AxisMappings=(AxisName=\"MoveRight\",Key=Gamepad_LeftX,Scale=1.f)\n\
AxisMappings=(AxisName=\"MoveRight\",Key=D,Scale=1.f)\n\
AxisMappings=(AxisName=\"MoveRight\",Key=A,Scale=-1.f)\n\
AxisMappings=(AxisName=\"MoveUp\",Key=Gamepad_LeftTrigger,Scale=1.f)\n\
AxisMappings=(AxisName=\"MoveUp\",Key=RightShift,Scale=1.f,bDebugOnly=True)\n\
AxisMappings=(AxisName=\"MoveUp\",Key=Gamepad_RightTrigger,Scale=-1.f)\n\
AxisMappings=(AxisName=\"MoveUp\",Key=RightControl,Scale=-1.f,bDebugOnly=True)\n\
AxisMappings=(AxisName=\"PhotoModeSlideUpDown\",Key=Gamepad_LeftY,Scale=1.f)\n\
AxisMappings=(AxisName=\"PhotoModeSlideUpDown\",Key=W,Scale=1.f,bDebugOnly=True)\n\
AxisMappings=(AxisName=\"PhotoModeSlideUpDown\",Key=S,Scale=-1.f,bDebugOnly=True)\n\
AxisMappings=(AxisName=\"PhotoModeSlideLeftRight\",Key=Gamepad_LeftX,Scale=1.f)\n\
AxisMappings=(AxisName=\"PhotoModeSlideLeftRight\",Key=A,Scale=-1.f,bDebugOnly=True)\n\
AxisMappings=(AxisName=\"PhotoModeSlideLeftRight\",Key=D,Scale=1.f,bDebugOnly=True)\n\
AxisMappings=(AxisName=\"Rotate\",Key=Gamepad_LeftShoulder,Scale=-1.f)\n\
AxisMappings=(AxisName=\"Rotate\",Key=H,Scale=-1.f)\n\
AxisMappings=(AxisName=\"Rotate\",Key=Gamepad_RightShoulder,Scale=1.f)\n\
AxisMappings=(AxisName=\"Rotate\",Key=J,Scale=1.f)\n\
AxisMappings=(AxisName=\"TripleMoveRight\",Key=Gamepad_DPad_Left,Scale=-1.f)\n\
AxisMappings=(AxisName=\"TripleMoveRight\",Key=Left,Scale=-1.f)\n\
AxisMappings=(AxisName=\"TripleMoveRight\",Key=Gamepad_DPad_Right,Scale=1.f)\n\
AxisMappings=(AxisName=\"TripleMoveRight\",Key=Right,Scale=1.f)\n\
AxisMappings=(AxisName=\"TripleMoveUp\",Key=Gamepad_DPad_Up,Scale=1.f)\n\
AxisMappings=(AxisName=\"TripleMoveUp\",Key=Up,Scale=1.f)\n\
AxisMappings=(AxisName=\"TripleMoveUp\",Key=Gamepad_DPad_Down,Scale=-1.f)\n\
AxisMappings=(AxisName=\"TripleMoveUp\",Key=Down,Scale=-1.f)\n\
AxisMappings=(AxisName=\"Turn\",Key=K,Scale=1.f)\n\
AxisMappings=(AxisName=\"Turn\",Key=Gamepad_RightX,Scale=-1.f)\n\
AxisMappings=(AxisName=\"Turn\",Key=Semicolon,Scale=-1.f)\n\
AxisMappings=(AxisName=\"TurnMouse\",Key=MouseX,Scale=-1.f,bDebugOnly=True)\n\
AxisMappings=(AxisName=\"UILeftX\",Key=Gamepad_LeftX,Scale=1.f)\n\
AxisMappings=(AxisName=\"UILeftX\",Key=D,Scale=1.f)\n\
AxisMappings=(AxisName=\"UILeftX\",Key=A,Scale=-1.f)\n\
AxisMappings=(AxisName=\"UILeftY\",Key=Gamepad_LeftY,Scale=1.f)\n\
AxisMappings=(AxisName=\"UILeftY\",Key=W,Scale=1.f)\n\
AxisMappings=(AxisName=\"UILeftY\",Key=S,Scale=-1.f)\n\
AxisMappings=(AxisName=\"UIRightX\",Key=K,Scale=-1.f)\n\
AxisMappings=(AxisName=\"UIRightX\",Key=Gamepad_RightX,Scale=1.f)\n\
AxisMappings=(AxisName=\"UIRightX\",Key=Semicolon,Scale=1.f)\n\
AxisMappings=(AxisName=\"UIRightY\",Key=Gamepad_RightY,Scale=1.f)\n\
AxisMappings=(AxisName=\"UIRightY\",Key=L,Scale=1.f)\n\
AxisMappings=(AxisName=\"UIRightY\",Key=O,Scale=-1.f)\n\
AxisMappings=(AxisName=\"UIWheelAxis\",Key=Gamepad_RightY,Scale=-1.f)\n\
AxisMappings=(AxisName=\"UIWheelAxis\",Key=L,Scale=-1.f)\n\
AxisMappings=(AxisName=\"UIWheelAxis\",Key=O,Scale=1.f)\n\
AxisMappings=(AxisName=\"DebugCamera_MoveForward\",Key=Gamepad_LeftY,Scale=1.f)\n\
AxisMappings=(AxisName=\"DebugCamera_MoveForward\",Key=W,Scale=1.f)\n\
AxisMappings=(AxisName=\"DebugCamera_MoveForward\",Key=S,Scale=-1.f)\n\
AxisMappings=(AxisName=\"DebugCamera_MoveRight\",Key=Gamepad_LeftX,Scale=1.f)\n\
AxisMappings=(AxisName=\"DebugCamera_MoveRight\",Key=D,Scale=1.f)\n\
AxisMappings=(AxisName=\"DebugCamera_MoveRight\",Key=A,Scale=-1.f)\n\
AxisMappings=(AxisName=\"DebugCamera_MoveUp\",Key=Gamepad_LeftTrigger,Scale=-1.f)\n\
AxisMappings=(AxisName=\"DebugCamera_MoveUp\",Key=Q,Scale=-1.f)\n\
AxisMappings=(AxisName=\"DebugCamera_MoveUp\",Key=Gamepad_RightTrigger,Scale=1.f)\n\
AxisMappings=(AxisName=\"DebugCamera_MoveUp\",Key=E,Scale=1.f)\n\
";
